server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
  flyway:
    user: sa
    password: password
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    locations: classpath:db/migration/h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  devtools:
    restart:
      enabled: true
  application:
    name: Trade Reporting Engine
  main:
    web-application-type: servlet
  h2:
    console:
      enabled: true

trading:
  title: Trade Reporting Engine
  filters:
    - name: EMU_BANK
      currency: AUD
    - name: BISON_BANK
      currency: USD

logging:
  level:
    root: INFO

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
  flyway:
    user: sa
    password: password
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    locations: classpath:db/migration/h2

springdoc:
  show-actuator: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: sa
    password: password
    url: jdbc:postgresql://trading:5432/trading
  flyway:
    user: sa
    password: password
    url: jdbc:postgresql://trading:5432/trading
    locations: classpath:db/migration/pgsql
  devtools:
    restart:
      enabled: false

springdoc:
  show-actuator: false
